global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'crewlife-apps'
    static_configs:
      - targets: ['crewlife-app-1:5000', 'crewlife-app-2:5000', 'crewlife-app-3:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'crewlife-monitor'
    static_configs:
      - targets: ['crewlife-web-monitor:5001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mariadb:9104']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
